### ISSUE TITLE
How to create environment for MitoS-segmentation-tool on Mac OS (M1)

### ISSUE THREAD

**Issue by MitoTAIKI** [MitoSegNet/MitoSegNet#3]
conda create -n "name" python==3.7

conda activate "name"

pip install keras==2.3.0

conda install tensorflow==1.14.0

pip install opencv-python

conda install matplotlib

conda install scikit-image

conda install pandas

conda install seaborn

**Comment by pillow1510** [comment]
hi!
I'm a apple M3 mac user. I have set up a conda env under subdir osx-64.  All the packages versions here you listed is installed.
Following info show up after run "MitoS_Main_CPU.py": 


> Using TensorFlow backend.
> /opt/anaconda3/envs/py37_osx64/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])

then GUI appears. After Predict using pretrained model, I got a empty Prediction folder and following info:

> ------------------------------
> Load test images...
> ------------------------------
> (?, 656, 656, 1) <class 'tensorflow.python.framework.ops.Tensor'>
> conv1 shape: (?, 656, 656, 64)
> 2025-03-26 00:28:27.207234: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
> To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
> 2025-03-26 00:28:27.207852: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 16. Tune using inter_op_parallelism_threads for best performance.
> conv1 shape: (?, 656, 656, 64)
> pool1 shape: (?, 328, 328, 64)
> conv2 shape: (?, 328, 328, 128)
> conv2 shape: (?, 328, 328, 128)
> pool2 shape: (?, 164, 164, 128)
> conv3 shape: (?, 164, 164, 256)
> conv3 shape: (?, 164, 164, 256)
> pool3 shape: (?, 82, 82, 256)
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/py37_osx64/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "/Users/Zhuanz/Desktop/tools/MitoS-segmentation-tool-master/MitoS_Main_CPU.py", line 909, in start_prediction_pretrained
>     p_pt_root)
>   File "/Users/Zhuanz/Desktop/tools/MitoS-segmentation-tool-master/MitoS_Main_CPU.py", line 245, in prediction
>     y_res)
>   File "/Users/Zhuanz/Desktop/tools/MitoS-segmentation-tool-master/MitoS_Train_Predict_CPU.py", line 567, in predict
>     model.load_weights(pretrain)
>   File "/opt/anaconda3/envs/py37_osx64/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
>     return load_function(*args, **kwargs)
>   File "/opt/anaconda3/envs/py37_osx64/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
>     f, self.layers, reshape=reshape)
>   File "/opt/anaconda3/envs/py37_osx64/lib/python3.7/site-packages/keras/engine/saving.py", line 1180, in load_weights_from_hdf5_group
>     original_keras_version = f.attrs['keras_version'].decode('utf8')
> AttributeError: 'str' object has no attribute 'decode'


Could anybody help me with that? Don't know what was happening.
